import AppIntents
import Foundation

/// Siri and Shortcuts open the same editable, provider-backed search UI.
/// No lyrics or timestamps are generated by an intent or language model.
@available(macOS 15.0, *)
struct SearchLyricsIntent: AppIntent {
    static let title: LocalizedStringResource = "Search Lyrics"
    static let description = IntentDescription("Search for lyrics for the current song in Muses.")
    static let openAppWhenRun = true

    @Parameter(title: "Song title or keywords", default: "")
    var query: String

    private var requestSearch: @MainActor @Sendable (String) -> Void = {
        MusesSingleInstance.requestLyricsSearch($0)
    }

    init() {}

    /// Tests bind a request receiver instead of presenting an AppKit window.
    @MainActor
    init(requestSearch: @escaping @MainActor @Sendable (String) -> Void) {
        self.requestSearch = requestSearch
    }

    @MainActor
    func perform() async throws -> some IntentResult {
        requestSearch(String(query.prefix(400)).trimmingCharacters(in: .whitespacesAndNewlines))
        return .result()
    }
}

struct LyricsSearchRoute: Equatable, Sendable {
    let query: String
    init?(url: URL) {
        guard url.scheme == "muses", url.host == "lyrics", url.user == nil, url.password == nil,
              url.port == nil, url.path.isEmpty || url.path == "/",
              let items = URLComponents(url: url, resolvingAgainstBaseURL: false)?.queryItems,
              items.count == 1, items[0].name == "q", let value = items[0].value,
              value.count <= 400 else { return nil }
        query = value.trimmingCharacters(in: .whitespacesAndNewlines)
    }
}
