import AppIntents
import Foundation

/// Siri and Shortcuts open the same editable, provider-backed search UI.
/// No lyrics or timestamps are generated by an intent or language model.
@available(macOS 15.0, *)
struct SearchLyricsIntent: AppIntent {
    static let title: LocalizedStringResource = "Search Lyrics"
    static let description = IntentDescription("Search for lyrics for the current song in Muses.")
    static let openAppWhenRun = true

    @Parameter(title: "Song title or keywords", default: "")
    var query: String

    func perform() async throws -> some IntentResult & OpensIntent {
        var components = URLComponents()
        components.scheme = "muses"
        components.host = "lyrics"
        components.queryItems = [.init(name: "q", value: String(query.prefix(400)))]
        return .result(opensIntent: OpenURLIntent(components.url!))
    }
}

struct LyricsSearchRoute: Equatable, Sendable {
    let query: String
    init?(url: URL) {
        guard url.scheme == "muses", url.host == "lyrics", url.user == nil, url.password == nil,
              url.port == nil, url.path.isEmpty || url.path == "/",
              let items = URLComponents(url: url, resolvingAgainstBaseURL: false)?.queryItems,
              items.count == 1, items[0].name == "q", let value = items[0].value,
              value.count <= 400 else { return nil }
        query = value.trimmingCharacters(in: .whitespacesAndNewlines)
    }
}
